sudo: false

language: python

python:
  - 3.6

env:
  global:
    - REPO=$(basename $TRAVIS_REPO_SLUG)
    - MINICONDA=$HOME/miniconda

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $MINICONDA
  - export PATH="$MINICONDA/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - sed -i "/python/c python=${TRAVIS_PYTHON_VERSION}" conda_environment.yml
  - sed -i -e '/nb_conda/d' -e '/jupyter/d' conda_environment.yml
  - echo "  - nomkl" >> conda_environment.yml
  - conda env create -f conda_environment.yml
  - source activate $REPO

install:
  - export PYTHONPATH=$PYTHONPATH:$PWD

script:
  - nosetests --cover-package=$REPO --with-coverage

after_success:
  - codecov
