sudo: false

language: python

python:
  - 3.6

env:
  global:
    - REPO=$(basename $TRAVIS_REPO_SLUG)

cache: pip

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda info -a
  # - conda create -n $REPO python=$TRAVIS_PYTHON_VERSION
  # - source activate $REPO
  # - conda install nomkl --file requirements.txt
  # - pip install codecov
  - conda env create -f conda_environment.yml
  - conda activate nuts
  - export PYTHONPATH=$PYTHONPATH:$PWD


script:
  - nosetests --cover-package=$REPO --with-coverage

after_success:
  - codecov
