sudo: false

language: python

python:
  - "3.6"

env:
  global:
    - REPO=nuts

cache: pip

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -n $REPO python=$TRAVIS_PYTHON_VERSION nomkl --file requirements.txt
  - source activate $REPO
  - conda update --all
  - pip install codecov
  - pip install .

script:
  - nosetests --cover-package=$REPO --with-coverage

after_success:
  - codecov
